# ===========================
# SHARED CONFIGURATION - applies to all services
# ===========================

spring:
  flyway:
    enabled: true
    locations: classpath:db/migration
    baseline-on-migrate: true
  jpa:
    hibernate:
      ddl-auto: validate
    show-sql: false
    properties:
      hibernate:
        format_sql: false
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    hikari:
      properties:
        useSSL: false
        allowPublicKeyRetrieval: true

springdoc:
  swagger-ui:
    path: /swagger-ui.html
    enabled: false
  api-docs:
    path: /v3/api-docs
    enabled: false

logging:
  level:
    root: WARN
    org.springframework: WARN
