services:

  config-server:
    build:
      context: .
      dockerfile: config-server/Dockerfile
    image: config-server
    container_name: config-server
    ports:
      - "8888:8888"
    environment:
      API_GATEWAY_TOKEN: ${API_GATEWAY_TOKEN}
    volumes:
      - ./config-repo:/config-repo
    healthcheck:
      test: ["CMD", "curl", "-sf", "http://localhost:8888/actuator/health"]
      start_period: 20s
      interval: 5s
      timeout: 3s
      retries: 3
    networks:
      - library-network

  mysql-db:
    image: mysql:8.0
    container_name: mysql-db
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
    volumes:
      - ./mysql/init.sql:/docker-entrypoint-initdb.d/init.sql
      - mysql-data:/var/lib/mysql
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      interval: 10s
      timeout: 5s
      retries: 5
    networks:
      - library-network

  book-service:
    build:
      context: ./book-service
    image: book-service
    container_name: book-service
    environment:
      SPRING_DATASOURCE_URL: ${SPRING_DATASOURCE_URL_BOOK}
      SPRING_DATASOURCE_USERNAME: ${MYSQL_USER}
      SPRING_DATASOURCE_PASSWORD: ${MYSQL_PASSWORD}
    depends_on:
      config-server:
        condition: service_healthy
      mysql-db:
        condition: service_healthy
    networks:
      - library-network

  member-service:
    build:
      context: ./member-service
    image: member-service
    container_name: member-service
    environment:
      SPRING_DATASOURCE_URL: ${SPRING_DATASOURCE_URL_MEMBER}
      SPRING_DATASOURCE_USERNAME: ${MYSQL_USER}
      SPRING_DATASOURCE_PASSWORD: ${MYSQL_PASSWORD}
    depends_on:
      config-server:
        condition: service_healthy
      mysql-db:
        condition: service_healthy
    networks:
      - library-network

  loan-service:
    build:
      context: ./loan-service
    image: loan-service
    container_name: loan-service
    environment:
      SPRING_DATASOURCE_URL: ${SPRING_DATASOURCE_URL_LOAN}
      SPRING_DATASOURCE_USERNAME: ${MYSQL_USER}
      SPRING_DATASOURCE_PASSWORD: ${MYSQL_PASSWORD}
    depends_on:
      config-server:
        condition: service_healthy
      mysql-db:
        condition: service_healthy
      book-service:
        condition: service_started
      member-service:
        condition: service_started
    networks:
      - library-network

  api-gateway:
    build:
      context: ./api-gateway
    image: api-gateway
    container_name: api-gateway
    ports:
      - "8080:8080"
    environment:
      API_GATEWAY_TOKEN: ${API_GATEWAY_TOKEN}
    depends_on:
      config-server:
        condition: service_healthy
    networks:
      - library-network

volumes:
  mysql-data:

networks:
  library-network:
    driver: bridge
