spring:
  application:
    name: api-gateway
  config:
    import: configserver:http://config-server:8888
  cloud:
    config:
      fail-fast: true
      retry:
        initial-interval: 2000
        multiplier: 1.5
        max-interval: 30000
        max-attempts: 10
