server.port=8082

spring.datasource.url=jdbc:mysql://localhost:3307/member_service_db
spring.datasource.username=librarian
spring.datasource.password=Libr@ry2026
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

spring.application.name=member-service
