spring.application.name=loan-service

# ===========================
# SERVER CONFIG
# ===========================
server.port=8083

# ===========================
# DATABASE CONFIG (solo variabili d'ambiente)
# ===========================
spring.datasource.url=${SPRING_DATASOURCE_URL}
spring.datasource.username=${SPRING_DATASOURCE_USERNAME}
spring.datasource.password=${SPRING_DATASOURCE_PASSWORD}
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

# ===========================
# MICROSERVICES ENDPOINTS
# ===========================
microservices.book-service.url=${MICROSERVICES_BOOK-SERVICE_URL}
microservices.member-service.url=${MICROSERVICES_MEMBER-SERVICE_URL}
